import pytest

from phase2.codex_transformation_executor import execute_codex_transformation
from phase2.ddl_parser import parse_ddl
from phase2.postgres_loader import PostgresLoadError
from phase2.warehouse_pipeline_planner import build_warehouse_pipeline_plan


def test_codex_transformation_executor_reports_setup_failure(monkeypatch):
    model = parse_ddl("CREATE TABLE load_customer_raw (customer_id varchar(20));")
    plan = build_warehouse_pipeline_plan(model)
    monkeypatch.setattr("phase2.codex_transformation_executor._require_psycopg", lambda: (_ for _ in ()).throw(PostgresLoadError("psycopg unavailable")))
    result = execute_codex_transformation(model, {"load_table_rows": {}}, plan)
    assert result["status"] == "failed"
    assert "psycopg unavailable" in result["errors"][0]

from phase2.codex_transformation_executor import (
    _default_result,
    _execute_sql_group,
    _insert_load_rows,
    _normalize_sql_for_target_schema,
)
from phase2.postgres_loader import _column_ddl


def test_normalize_sql_rewrites_only_known_schema_qualified_tables():
    model = parse_ddl("""
CREATE TABLE raw.load_customer (load_id integer PRIMARY KEY, customer_id text);
CREATE TABLE stg.stg_customer (customer_id text);
CREATE TABLE dw.fact_delivery (delivery_key integer PRIMARY KEY, customer_id text);
""")
    statement = """
INSERT INTO dw.fact_delivery (customer_id)
SELECT s.customer_id
FROM stg.stg_customer s
JOIN raw.load_customer r ON r.customer_id = s.customer_id
JOIN audit.unknown_table u ON u.customer_id = s.customer_id
WHERE raw.load_customer.customer_id = s.customer_id
  AND 'raw.load_customer' = 'raw.load_customer';
"""
    normalized = _normalize_sql_for_target_schema(statement, model, "grocery_online_shopping")
    assert '"grocery_online_shopping"."fact_delivery"' in normalized
    assert '"grocery_online_shopping"."stg_customer"' in normalized
    assert '"grocery_online_shopping"."load_customer"' in normalized
    assert '"grocery_online_shopping"."load_customer".customer_id' in normalized
    assert "audit.unknown_table" in normalized
    assert normalized.count("'raw.load_customer'") == 2


class _RecordingCursor:
    def __init__(self, calls):
        self.calls = calls

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, tb):
        return False

    def executemany(self, query, values):
        self.calls.append((repr(query), values))


class _RecordingConnection:
    def __init__(self):
        self.calls = []

    def cursor(self):
        return _RecordingCursor(self.calls)

    def execute(self, statement):
        self.calls.append((statement, None))


class _FakeSqlValue:
    def __init__(self, value):
        self.value = str(value)

    def __add__(self, other):
        return _FakeSqlValue(self.value + other.value)

    def format(self, *args):
        rendered = self.value
        for arg in args:
            rendered = rendered.replace("{}", arg.value, 1)
        return _FakeSqlValue(rendered)

    def join(self, values):
        return _FakeSqlValue(self.value.join(value.value for value in values))

    def as_string(self):
        return self.value

    def __repr__(self):
        return self.value


class _FakeSqlModule:
    SQL = _FakeSqlValue

    @staticmethod
    def Identifier(value):
        return _FakeSqlValue(f'"{value}"')

    @staticmethod
    def Placeholder():
        return _FakeSqlValue("%s")


def test_insert_load_rows_omits_missing_identity_or_default_columns(monkeypatch):
    monkeypatch.setattr("phase2.codex_transformation_executor.sql", _FakeSqlModule)
    model = parse_ddl("""
CREATE TABLE raw.load_customer (
    load_id integer PRIMARY KEY,
    customer_id text NOT NULL,
    loaded_at timestamp DEFAULT CURRENT_TIMESTAMP
);
""")
    conn = _RecordingConnection()
    inserted = _insert_load_rows(
        conn,
        model,
        "grocery_online_shopping",
        {"load_customer": [{"customer_id": "C1"}]},
    )
    assert inserted == {"load_customer": 1}
    assert len(conn.calls) == 1
    query_repr, values = conn.calls[0]
    assert "customer_id" in query_repr
    assert "load_id" not in query_repr
    assert "loaded_at" not in query_repr
    assert values == [["C1"]]


def test_integer_primary_key_without_default_becomes_identity(monkeypatch):
    monkeypatch.setattr("phase2.postgres_loader.sql", _FakeSqlModule)
    model = parse_ddl("CREATE TABLE sample (sample_key integer PRIMARY KEY, name text);")
    rendered = _column_ddl(model.tables[0].columns[0]).as_string()
    assert "GENERATED BY DEFAULT AS IDENTITY" in rendered


def test_execute_sql_group_records_and_executes_normalized_sql(monkeypatch):
    monkeypatch.setattr("phase2.codex_transformation_executor.sql", _FakeSqlModule)
    model = parse_ddl("""
CREATE TABLE raw.load_customer (customer_id text);
CREATE TABLE stg.stg_customer (customer_id text);
""")
    connection = _RecordingConnection()
    result = _default_result()
    _execute_sql_group(
        connection,
        "grocery_online_shopping",
        model,
        [
            "INSERT INTO stg.stg_customer (customer_id) "
            "SELECT customer_id FROM raw.load_customer;"
        ],
        "staging_sql",
        result,
    )
    normalized = result["executed_sql"]["staging_sql"][0]
    assert normalized == result["failing_sql"]
    assert '"grocery_online_shopping"."stg_customer"' in normalized
    assert '"grocery_online_shopping"."load_customer"' in normalized
    assert any(call[0] == normalized for call in connection.calls)
