from __future__ import annotations

import json
import os
import re

from runtime_config import PROTECTED_SCHEMAS, load_project_env

try:
    import psycopg
    from psycopg import sql
    try:
        from psycopg.types.json import Jsonb
    except ImportError:  # pragma: no cover
        Jsonb = None
except ImportError:  # pragma: no cover
    psycopg = None
    sql = None
    Jsonb = None

from .synthetic_data_generator import table_generation_order


class PostgresLoadError(Exception):
    pass


def _require_psycopg():
    if psycopg is None or sql is None:
        raise PostgresLoadError(
            "psycopg is required for PostgreSQL loading. "
            "Install dependencies with: python -m pip install -r requirements.txt"
        )


def _quote_type(data_type):
    return sql.SQL(data_type)


def _column_ddl(column):
    pieces = [sql.Identifier(column.name), _quote_type(column.data_type)]
    dtype = column.data_type.lower()
    integer_primary_key = (
        column.is_primary_key
        and column.default is None
        and re.search(r"\b(?:smallint|integer|bigint|int|int2|int4|int8)\b", dtype)
        and "serial" not in dtype
    )
    if integer_primary_key:
        pieces.append(sql.SQL("GENERATED BY DEFAULT AS IDENTITY"))
    elif column.default is not None:
        pieces.append(sql.SQL("DEFAULT ") + sql.SQL(column.default))
    if not column.nullable or column.is_primary_key:
        pieces.append(sql.SQL("NOT NULL"))
    return sql.SQL(" ").join(pieces)


def _adapt(value):
    if isinstance(value, (dict, list)):
        return Jsonb(value) if Jsonb is not None else json.dumps(value, sort_keys=True)
    return value


def load_env(target_schema: str | None = None):
    """Load connection settings and an approved per-use-case target schema."""
    load_project_env()
    required = [
        "POSTGRES_HOST",
        "POSTGRES_PORT",
        "POSTGRES_DB",
        "POSTGRES_USER",
        "POSTGRES_PASSWORD",
    ]
    missing = [key for key in required if not os.getenv(key)]
    if missing:
        raise PostgresLoadError(
            "Missing required PostgreSQL environment variable(s): "
            + ", ".join(missing)
        )
    schema = (target_schema or os.getenv("POSTGRES_TARGET_SCHEMA") or "").strip()
    if not schema:
        raise PostgresLoadError(
            "A target schema was not provided. Phase 2 should derive it from the YAML, "
            "or POSTGRES_TARGET_SCHEMA must be set."
        )
    if schema.lower() in PROTECTED_SCHEMAS or schema.lower().startswith("pg_"):
        raise PostgresLoadError(f"Unsafe PostgreSQL target schema: {schema}")
    try:
        port = int(os.getenv("POSTGRES_PORT", "5432"))
        connect_timeout = int(os.getenv("POSTGRES_CONNECT_TIMEOUT", "15"))
    except ValueError as exc:
        raise PostgresLoadError(
            "POSTGRES_PORT and POSTGRES_CONNECT_TIMEOUT must be integers."
        ) from exc
    return {
        "host": os.environ["POSTGRES_HOST"],
        "port": port,
        "dbname": os.environ["POSTGRES_DB"],
        "user": os.environ["POSTGRES_USER"],
        "password": os.environ["POSTGRES_PASSWORD"],
        "sslmode": os.getenv("POSTGRES_SSLMODE", "prefer"),
        "connect_timeout": connect_timeout,
        "target_schema": schema,
    }


def _connect(cfg):
    return psycopg.connect(
        host=cfg["host"],
        port=cfg["port"],
        dbname=cfg["dbname"],
        user=cfg["user"],
        password=cfg["password"],
        sslmode=cfg["sslmode"],
        connect_timeout=cfg["connect_timeout"],
        application_name="data_model_accelerator",
    )


def preflight_postgres(
    target_schema: str,
    *,
    require_schema_create: bool = True,
    recreate_schema: bool = False,
) -> dict:
    """Fail fast before Codex generation when PostgreSQL is unreachable or unauthorized."""
    _require_psycopg()
    cfg = load_env(target_schema)
    try:
        with _connect(cfg) as conn:
            conn.execute("SELECT 1").fetchone()
            existing = conn.execute(
                "SELECT 1 FROM information_schema.schemata WHERE schema_name = %s",
                [target_schema],
            ).fetchone()
            if existing:
                has_usage = conn.execute(
                    "SELECT has_schema_privilege(current_user, %s, 'USAGE')",
                    [target_schema],
                ).fetchone()[0]
                has_create = conn.execute(
                    "SELECT has_schema_privilege(current_user, %s, 'CREATE')",
                    [target_schema],
                ).fetchone()[0]
                if not has_usage or (require_schema_create and not has_create):
                    raise PostgresLoadError(
                        f"PostgreSQL user lacks required privileges on schema {target_schema}. "
                        "USAGE and CREATE are required."
                    )
                if recreate_schema:
                    can_drop = conn.execute(
                        "SELECT pg_get_userbyid(n.nspowner) = current_user "
                        "OR COALESCE((SELECT rolsuper FROM pg_roles WHERE rolname = current_user), false) "
                        "FROM pg_namespace n WHERE n.nspname = %s",
                        [target_schema],
                    ).fetchone()[0]
                    if not can_drop:
                        raise PostgresLoadError(
                            f"PostgreSQL user does not own schema {target_schema}; "
                            "clean recreate mode cannot safely replace it."
                        )
            elif require_schema_create:
                can_create = conn.execute(
                    "SELECT has_database_privilege(current_user, current_database(), 'CREATE')"
                ).fetchone()[0]
                if not can_create:
                    raise PostgresLoadError(
                        f"PostgreSQL user cannot create target schema {target_schema}. "
                        "Grant CREATE on the database or pre-create the schema."
                    )
        return {
            "status": "passed",
            "target_schema": target_schema,
            "database": cfg["dbname"],
            "host": cfg["host"],
            "port": cfg["port"],
        }
    except PostgresLoadError:
        raise
    except Exception as exc:
        raise PostgresLoadError(
            f"PostgreSQL preflight failed for {cfg['host']}:{cfg['port']}/"
            f"{cfg['dbname']}: {exc}"
        ) from exc


def _create_table(conn, table, schema):
    column_defs = [_column_ddl(column) for column in table.columns]
    constraints = []
    if table.primary_key:
        constraints.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(sql.Identifier(col) for col in table.primary_key)
            )
        )
    for unique in getattr(table, "unique_constraints", []):
        constraints.append(
            sql.SQL("UNIQUE ({})").format(
                sql.SQL(", ").join(sql.Identifier(col) for col in unique.columns)
            )
        )
    for check in getattr(table, "check_constraints", []):
        if getattr(check, "supported", False):
            constraints.append(sql.SQL("CHECK ({})").format(sql.SQL(check.expression)))
    for fk in table.foreign_keys:
        constraints.append(
            sql.SQL("FOREIGN KEY ({}) REFERENCES {}.{} ({})").format(
                sql.SQL(", ").join(sql.Identifier(col) for col in fk.child_columns),
                sql.Identifier(schema),
                sql.Identifier(fk.parent_table),
                sql.SQL(", ").join(sql.Identifier(col) for col in fk.parent_columns),
            )
        )
    ddl = sql.SQL("CREATE TABLE IF NOT EXISTS {}.{} ({})").format(
        sql.Identifier(schema),
        sql.Identifier(table.name),
        sql.SQL(", ").join(column_defs + constraints),
    )
    conn.execute(ddl)


def load_to_postgres(
    model,
    data,
    *,
    target_schema: str | None = None,
    create_schema_if_missing=False,
    create_tables_if_missing=False,
    truncate_before_load=False,
    allow_insert_into_nonempty_tables=False,
):
    _require_psycopg()
    cfg = {}
    inserted = {}
    errors = []
    schema_status = "not_attempted"
    table_status = "not_attempted"
    transaction_status = "not_started"
    try:
        cfg = load_env(target_schema)
        with _connect(cfg) as conn:
            try:
                if create_schema_if_missing:
                    conn.execute(
                        sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                            sql.Identifier(cfg["target_schema"])
                        )
                    )
                    schema_status = "created_or_already_exists"
                else:
                    exists = conn.execute(
                        "SELECT 1 FROM information_schema.schemata WHERE schema_name = %s",
                        [cfg["target_schema"]],
                    ).fetchone()
                    schema_status = "exists" if exists else "missing"
                    if not exists:
                        raise PostgresLoadError(
                            f"Target schema {cfg['target_schema']} does not exist."
                        )

                for table in table_generation_order(model):
                    exists = conn.execute(
                        "SELECT 1 FROM information_schema.tables "
                        "WHERE table_schema = %s AND table_name = %s",
                        [cfg["target_schema"], table.name],
                    ).fetchone()
                    if not exists:
                        if create_tables_if_missing:
                            _create_table(conn, table, cfg["target_schema"])
                            table_status = "created_missing_tables"
                        else:
                            raise PostgresLoadError(
                                f"Table {cfg['target_schema']}.{table.name} does not exist."
                            )
                    count = conn.execute(
                        sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
                            sql.Identifier(cfg["target_schema"]),
                            sql.Identifier(table.name),
                        )
                    ).fetchone()[0]
                    if count and not truncate_before_load and not allow_insert_into_nonempty_tables:
                        raise PostgresLoadError(
                            f"Table {cfg['target_schema']}.{table.name} is non-empty."
                        )
                    if exists and table_status == "not_attempted":
                        table_status = "all_tables_exist"
                    if truncate_before_load:
                        conn.execute(
                            sql.SQL("TRUNCATE TABLE {}.{} CASCADE").format(
                                sql.Identifier(cfg["target_schema"]),
                                sql.Identifier(table.name),
                            )
                        )

                transaction_status = "in_progress"
                for table in table_generation_order(model):
                    columns = table.column_names()
                    insert = sql.SQL("INSERT INTO {}.{} ({}) VALUES ({})").format(
                        sql.Identifier(cfg["target_schema"]),
                        sql.Identifier(table.name),
                        sql.SQL(", ").join(sql.Identifier(col) for col in columns),
                        sql.SQL(", ").join(sql.Placeholder() for _ in columns),
                    )
                    values = [
                        [_adapt(row.get(col)) for col in columns]
                        for row in data[table.name]
                    ]
                    with conn.cursor() as cur:
                        cur.executemany(insert, values)
                    inserted[table.name] = len(values)
                conn.commit()
                transaction_status = "committed"
            except Exception:
                conn.rollback()
                inserted = {}
                transaction_status = "rolled_back"
                raise
    except Exception as exc:
        errors.append(str(exc))
        return {
            "status": "failed",
            "target_schema": cfg.get("target_schema", ""),
            "inserted_rows": inserted,
            "errors": errors,
            "schema_creation_status": schema_status,
            "table_creation_status": table_status,
            "transaction_status": transaction_status,
        }
    return {
        "status": "passed",
        "target_schema": cfg["target_schema"],
        "inserted_rows": inserted,
        "errors": [],
        "schema_creation_status": schema_status,
        "table_creation_status": table_status,
        "transaction_status": transaction_status,
    }


def validate_postgres_load(model, expected_counts, *, target_schema: str | None = None):
    _require_psycopg()
    cfg = load_env(target_schema)
    errors = []
    row_counts = {}
    with _connect(cfg) as conn:
        for table in model.tables:
            actual = conn.execute(
                sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
                    sql.Identifier(cfg["target_schema"]),
                    sql.Identifier(table.name),
                )
            ).fetchone()[0]
            expected = expected_counts.get(table.name, 0)
            row_counts[table.name] = {"expected": expected, "actual": actual}
            if actual < expected:
                errors.append(
                    f"{table.name}: expected at least {expected} rows, found {actual}."
                )
            for fk in table.foreign_keys:
                conditions = [
                    sql.SQL("c.{} IS NOT NULL").format(sql.Identifier(col))
                    for col in fk.child_columns
                ]
                joins = [
                    sql.SQL("c.{} = p.{}").format(
                        sql.Identifier(child), sql.Identifier(parent)
                    )
                    for child, parent in zip(fk.child_columns, fk.parent_columns)
                ]
                query = sql.SQL(
                    "SELECT COUNT(*) FROM {}.{} c LEFT JOIN {}.{} p ON {} "
                    "WHERE {} AND p.{} IS NULL"
                ).format(
                    sql.Identifier(cfg["target_schema"]),
                    sql.Identifier(table.name),
                    sql.Identifier(cfg["target_schema"]),
                    sql.Identifier(fk.parent_table),
                    sql.SQL(" AND ").join(joins),
                    sql.SQL(" AND ").join(conditions),
                    sql.Identifier(fk.parent_columns[0]),
                )
                orphan_count = conn.execute(query).fetchone()[0]
                if orphan_count:
                    errors.append(
                        f"{table.name}: {orphan_count} orphan rows for FK to "
                        f"{fk.parent_table}."
                    )
    return {
        "status": "passed" if not errors else "failed",
        "errors": errors,
        "row_counts": row_counts,
    }
